server:
  port: 3000

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  data:
    mongodb:
      repositories:
        enabled: true
      uri: mongodb://${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/${MONGO_DB_COLLECTION:logs}

rabbit:
  exchange:
    log-data: log-data.topic

  routingkey:
    log-data: log-data.routingkey

  queue:
    log-data: log-data.queue