server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  data:
    mongodb:
      repositories:
        enabled: true
      uri: mongodb://${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/${MONGO_DB_COLLECTION:decision-engine}

app-config:
  services:
    cpf:
      uri: http://localhost:8081/api/v1/cpf/
      valid: ${app-config.services.cpf.uri}%s/valido
      clean: ${app-config.services.cpf.uri}%s/limpo

    cep:
      uri: http://localhost:8082/api/v1/cep/%s

    idade:
      uri: http://localhost:8083/api/v1/idade/%s

rabbit:
  exchange:
    log-data: log-data.topic

  routingkey:
    log-data: log-data.routingkey

  queue:
    log-data: log-data.queue