spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  data:
    mongodb:
      repositories:
        enabled: true
      uri: mongodb://${MONGO_DB_HOST:localhost}:${MONGO_DB_PORT:27017}/${MONGO_DB_COLLECTION:decision-engine}
